import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BillItem, UserDetails, Translation } from '../types';

// Robust list of CDNs for Noto Sans Tamil
const FONT_URLS = [
  // jsDelivr - High availability CDN
  'https://cdn.jsdelivr.net/gh/google/fonts@main/ofl/notosanstamil/NotoSansTamil-Regular.ttf',
  // GitHub Raw - Direct source
  'https://raw.githubusercontent.com/google/fonts/main/ofl/notosanstamil/NotoSansTamil-Regular.ttf',
  // Unpkg - Another reliable mirror
  'https://www.unpkg.com/@fontsource/noto-sans-tamil/files/noto-sans-tamil-tamil-400-normal.woff'
];

/**
 * Fetches the Tamil font as a Base64 string from available CDNs.
 */
const fetchFontBase64 = async (): Promise<string | null> => {
  for (const url of FONT_URLS) {
    try {
      const response = await fetch(url);
      if (response.ok) {
        const blob = await response.blob();
        return await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            const result = reader.result as string;
            // Strip the Data URI prefix to get raw Base64
            // e.g., "data:font/ttf;base64,AAEAAA..." -> "AAEAAA..."
            const base64 = result.split(',')[1];
            if (base64) resolve(base64);
            else reject('Invalid base64 conversion');
          };
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        });
      }
    } catch (error) {
      console.warn(`Attempt to load font from ${url} failed. Trying next...`);
    }
  }
  return null;
};

export const generatePDF = async (
  items: BillItem[],
  userDetails: UserDetails,
  t: Translation,
  grandTotal: number
) => {
  const doc = new jsPDF();
  const fontFileName = 'NotoSansTamil-Regular.ttf';
  const fontName = 'NotoSansTamil';
  let isFontLoaded = false;

  try {
    const base64Font = await fetchFontBase64();
    if (base64Font) {
      // 1. Add file to Virtual File System
      doc.addFileToVFS(fontFileName, base64Font);
      // 2. Register font (setup alias)
      doc.addFont(fontFileName, fontName, 'normal');
      // 3. Set as active font
      doc.setFont(fontName);
      isFontLoaded = true;
    } else {
      console.error("Failed to load Tamil font. PDF will use default font (Tamil characters may not render).");
    }
  } catch (err) {
    console.error("Error embedding font:", err);
  }

  const activeFont = isFontLoaded ? fontName : 'helvetica';

  // --- Header ---
  doc.setFont(activeFont); // Ensure font is set before writing text
  doc.setFontSize(22);
  doc.setTextColor(40);
  doc.text(t.title, 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 28);

  // --- User Details ---
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(t.userDetails, 14, 40);
  
  doc.setFontSize(10);
  doc.setTextColor(80);
  let yPos = 46;
  if (userDetails.name) {
    doc.text(`${userDetails.name}`, 14, yPos);
    yPos += 6;
  }
  if (userDetails.address) {
    doc.text(`${userDetails.address}`, 14, yPos);
    yPos += 6;
  }
  if (userDetails.mobile) {
    doc.text(`${userDetails.mobile}`, 14, yPos);
    yPos += 6;
  }
  if (userDetails.email) {
    doc.text(`${userDetails.email}`, 14, yPos);
  }

  // --- Table ---
  const tableColumn = [t.slNo, t.item, t.quantity, t.rate, t.total];
  const tableRows: any[] = [];

  items.forEach((item, index) => {
    const itemData = [
      index + 1,
      item.name,
      item.quantity,
      item.rate.toFixed(2),
      item.total.toFixed(2),
    ];
    tableRows.push(itemData);
  });

  // Footer Row
  tableRows.push([
    '', 
    '', 
    '', 
    { content: t.grandTotal, styles: { fontStyle: 'bold', font: activeFont } }, 
    { content: `Rs. ${grandTotal.toFixed(2)}`, styles: { fontStyle: 'bold', font: activeFont } }
  ]);

  autoTable(doc, {
    head: [tableColumn],
    body: tableRows,
    startY: 75,
    theme: 'grid',
    styles: {
      font: activeFont, // Apply to ALL cells
      fontSize: 10,
      cellPadding: 3,
      overflow: 'linebreak'
    },
    headStyles: {
      fillColor: [59, 130, 246], // Blue
      textColor: 255,
      font: activeFont,
      fontStyle: 'normal'
    },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 30 },
      3: { cellWidth: 30, halign: 'right' },
      4: { cellWidth: 35, halign: 'right' },
    },
  });

  // --- Footer ---
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("Generated by VoiceBill App", 14, finalY);

  doc.save(`Bill_${new Date().getTime()}.pdf`);
};