import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BillItem, UserDetails, Language, Translation } from '../types';
import { TAMIL_FONT_BASE64 } from './tamilFontBase64';

// Register Tamil font
const registerTamilFont = (doc: jsPDF): void => {
  doc.addFileToVFS('NotoSansTamil-Regular.ttf', TAMIL_FONT_BASE64);
  doc.addFont('NotoSansTamil-Regular.ttf', 'NotoSansTamil', 'normal', 'Identity-H');
};

export const generatePDF = (
  items: BillItem[],
  customer: UserDetails,
  grandTotal: number,
  language: Language,
  t: Translation
): void => {
  const doc = new jsPDF();
  
  // Register and set Tamil font
  registerTamilFont(doc);
  
  const isTamil = language === 'ta';
  const fontName = isTamil ? 'NotoSansTamil' : 'helvetica';
  
  // Page setup
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  
  // Colors
  const primaryColor: [number, number, number] = [0, 128, 128]; // Teal
  const darkColor: [number, number, number] = [33, 37, 41];
  const lightGray: [number, number, number] = [248, 249, 250];
  
  // ===== HEADER =====
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, pageWidth, 35, 'F');
  
  doc.setFont(fontName, 'normal');
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  const title = isTamil ? 'தினசரி வீட்டு பில்' : 'Daily Home Bill';
  doc.text(title, pageWidth / 2, 20, { align: 'center' });
  
  // Date
  doc.setFontSize(10);
  const today = new Date();
  const dateStr = today.toLocaleDateString(isTamil ? 'ta-IN' : 'en-IN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(dateStr, pageWidth / 2, 30, { align: 'center' });
  
  // ===== CUSTOMER INFO =====
  let yPos = 50;
  
  doc.setFillColor(...lightGray);
  doc.roundedRect(margin, yPos - 5, pageWidth - 2 * margin, 30, 3, 3, 'F');
  
  doc.setFont(fontName, 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...darkColor);
  
  const nameLabel = isTamil ? 'வாடிக்கையாளர்' : 'Customer';
  const phoneLabel = isTamil ? 'தொலைபேசி' : 'Mobile';
  
  doc.text(`${nameLabel}: ${customer.name || '-'}`, margin + 5, yPos + 8);
  doc.text(`${phoneLabel}: ${customer.mobile || '-'}`, margin + 5, yPos + 18);
  
  // ===== ITEMS TABLE =====
  yPos = 95;
  
  // Table headers - use Tamil text directly
  const headers = isTamil 
    ? [['வ.எண்', 'பொருள்', 'அளவு', 'விலை (₹)', 'மொத்தம் (₹)']]
    : [['S.No', 'Item', 'Qty', 'Rate (₹)', 'Total (₹)']];
  
  // Table body
  const tableBody = items.map((item, index) => [
    (index + 1).toString(),
    item.name,
    item.quantity.toString(),
    item.rate.toFixed(2),
    item.total.toFixed(2)
  ]);

  autoTable(doc, {
    startY: yPos,
    head: headers,
    body: tableBody,
    theme: 'grid',
    styles: {
      font: fontName,
      fontSize: 10,
      cellPadding: 5,
      lineColor: [200, 200, 200],
      lineWidth: 0.5,
    },
    headStyles: {
      font: fontName,
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: 'normal',
      halign: 'center',
    },
    bodyStyles: {
      font: fontName,
      textColor: darkColor,
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 20 },
      1: { halign: 'left', cellWidth: 60 },
      2: { halign: 'center', cellWidth: 25 },
      3: { halign: 'right', cellWidth: 35 },
      4: { halign: 'right', cellWidth: 35 },
    },
    margin: { left: margin, right: margin },
    didParseCell: (data) => {
      // Force Tamil font for all cells
      if (isTamil) {
        data.cell.styles.font = 'NotoSansTamil';
      }
    },
  });

  // Get final Y position after table
  const finalY = (doc as any).lastAutoTable?.finalY || yPos + 50;
  
  // ===== GRAND TOTAL =====
  yPos = finalY + 15;
  
  doc.setFillColor(...primaryColor);
  doc.roundedRect(pageWidth - margin - 80, yPos - 5, 80, 20, 3, 3, 'F');
  
  doc.setFont(fontName, 'normal');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  
  const totalLabel = isTamil ? 'மொத்தம்' : 'Total';
  doc.text(`${totalLabel}: ₹${grandTotal.toFixed(2)}`, pageWidth - margin - 75, yPos + 7);
  
  // ===== FOOTER =====
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFillColor(...lightGray);
  doc.rect(0, pageHeight - 20, pageWidth, 20, 'F');
  
  doc.setFont(fontName, 'normal');
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  
  const footerText = isTamil 
    ? 'VoiceBill மூலம் உருவாக்கப்பட்டது | நன்றி!'
    : 'Generated by VoiceBill | Thank you!';
  doc.text(footerText, pageWidth / 2, pageHeight - 8, { align: 'center' });
  
  // ===== SAVE PDF =====
  const fileName = `bill_${customer.name || 'customer'}_${today.toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
